### ISSUE TITLE
Error envío de un mensaje XML de alta inicial (“normal”) del registro de facturación

### ISSUE THREAD

**Issue by mdiago** [mdiago/VeriFactu#1]
En las pruebas iniciales de envío de mensajes al webservice, el servidor del entorno de pruebas de la AEAT está devolviendo el error 'Codigo[4102].El XML no cumple el esquema. Falta informar campo obligatorio.: BaseImponibleOimporteNoSujeto'.

Dicho campo se encuentra en el bloque de 'DetalleDesglose' del siguiente modo en la documentación:

![image](https://github.com/user-attachments/assets/a117ec11-741c-4c8b-af3b-aa909ffba6ee)

Y como se puede observar en el fichero xml del mensaje de envío generado por nosotros, está presente:

![image](https://github.com/user-attachments/assets/96d10500-3004-413a-8e9a-cf5d38500270)

El orden de los elementos del bloque 'DetalleDesglose' es el mismo que consta en el archivo de ejemplo de la documentación; por lo que no sabemos a qué puede ser debido el error.

Hemos enviado un mail al correo de soporte (verifactu@correo.aeat.es) notificando la incidencia (2024-10-12 10:32), y estamos a la espera de contestación.

**Comment by Jose-jin** [comment]
Hola, he descubierto qué es lo que pasa y el error lo da en Baseimponible, pero el problema es que la etiqueta DetalleDesglose está repetida, La etiqueta DetalleDesglose que engloba a las 2 de dentro si la quitas ya funciona correctamente. Por lo menos lo he hecho y me lo valida.

**Comment by mdiago** [comment]
Muchas gracias, hemos corregido el error en el bloque y ya funciona correctamente.
