### ISSUE TITLE
Me gustaria tener un ejemplo de como enviar una factura con cabecera de cliente con el regimen general y otra simplificada 

### ISSUE THREAD

**Issue by hcomputronic** [mdiago/VeriFactu#16]
Estoy usando su libreria y me gustaria saber un ejemplo de envio de una factura con cabecera de cliente con el regimen general y otro ejemplo con factura simplificada para cuando se facturan ticket de venta

**Comment by mdiago** [comment]
## Ejemplo factura simplificada (Tipo F2)

```C#

// Creamos una instacia de la clase factura
var invoice = new Invoice("GIT-EJ-F2-0050", new DateTime(2024, 12, 4), "B72877814")
{
    InvoiceType = TipoFactura.F2,
    SellerName = "WEFINZ GANDIA SL",
    Text = "PRESTACION SERVICIOS DESARROLLO SOFTWARE",
    TaxItems = new List<TaxItem>() {
        new TaxItem()
        {
            TaxRate = 4,
            TaxBase = 10,
            TaxAmount = 0.4m
        },
        new TaxItem()
        {
            TaxRate = 21,
            TaxBase = 100,
            TaxAmount = 21
        }
    }
};

// Creamos la entrada de la factura
var invoiceEntry = new InvoiceEntry(invoice);

// Guardamos la factura
invoiceEntry.Save();

// Consultamos el estado
Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.Status}");

if (invoiceEntry.Status == "Correcto")
{

    // Consultamos el CSV
    Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.CSV}");

}
else
{

    // Consultamos el error
    Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.ErrorCode}: {invoiceEntry.ErrorDescription}");

}

// Consultamos el resultado devuelto por la AEAT
Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.Response}");

```

**Comment by mdiago** [comment]
El ejemplo de envío de registro de alta de la wiki es de una factura en régimen general:

[Ejemplo Alta wiki](https://github.com/mdiago/VeriFactu/wiki#alta)

**Comment by hcomputronic** [comment]
Esto es por cada tipo de iva que lleve la factura simplificada del total, es decir solo se pone los diferentes base y cuotas de iva del importe total de la factura simplificada o hay que especificar todos los productos que lleve la factura simplificada con sus tipos de iva y base y cuota  Text = "PRESTACION SERVICIOS DESARROLLO SOFTWARE",
    TaxItems = new List<TaxItem>() {
        new TaxItem()
        {
            TaxRate = 4,
            TaxBase = 10,
            TaxAmount = 0.4m
        },
        new TaxItem()
        {
            TaxRate = 21,
            TaxBase = 100,
            TaxAmount = 21
        }

**Comment by mdiago** [comment]
Creo que en la introducción de la wiki se responde a estas dudas:

[https://github.com/mdiago/VeriFactu/wiki#verifactu-wiki](https://github.com/mdiago/VeriFactu/wiki#verifactu-wiki)

Si después de leerla no consideras resueltas tus dudas, por favor, dímelo e intentaré resolverlas. Gracias

**Comment by mdiago** [comment]
Verifactu no incluye líneas de factura, solo el detalle de bases y cuotas
