### ISSUE TITLE
Error Compilar v.1.0.12

### ISSUE THREAD

**Issue by PGSoftIberica** [mdiago/VeriFactu#18]
hola no me deja compilar me aparece este error
No se puede encontrar una parte de la ruta de acceso 'C:\Users\usuario\Desktop\TRABAJO\VeriFactu\NetFramework\bin\Debug'.

Un Saludo

**Comment by PGSoftIberica** [comment]
Buenos dias, ya solucione el error

hice estos cambios y se genero perfecto

<TfmSpecificPackageFile Include="C:\Users\usuario\Desktop\TRABAJO\VeriFactu\NetFramework\bin\Debug\VeriFactu.dll">
<TfmSpecificPackageFile Include="..\NetFramework\bin\Debug\VeriFactu.dll">

 <TfmSpecificPackageFile Include="C:\Users\usuario\Desktop\TRABAJO\VeriFactu\NetFramework\bin\Debug\VeriFactu.xml">
<TfmSpecificPackageFile Include="..\NetFramework\bin\Debug\VeriFactu.xml">

otra cosa en .net core cambie a .net 8 ya que el .net 7 me dice no compatible (con vs2022)
Un Saludo

**Comment by mdiago** [comment]
Hola, por favor, puedes decirnos qué cambios para que podamos revisarlo. Gracias.

**Comment by mdiago** [comment]
Nuget package probado con .NET Framework 4.8 y con .NET 7.0 funcionando

**Comment by PGSoftIberica** [comment]
estos cambios 

<TfmSpecificPackageFile Include="C:\Users\usuario\Desktop\TRABAJO\VeriFactu\NetFramework\bin\Debug\VeriFactu.dll">
<TfmSpecificPackageFile Include="..\NetFramework\bin\Debug\VeriFactu.dll">

 <TfmSpecificPackageFile Include="C:\Users\usuario\Desktop\TRABAJO\VeriFactu\NetFramework\bin\Debug\VeriFactu.xml">
<TfmSpecificPackageFile Include="..\NetFramework\bin\Debug\VeriFactu.xml">

**Comment by PGSoftIberica** [comment]
hola, hice esto
![solucion_verifactu](https://github.com/user-attachments/assets/6d96437a-a529-4115-883b-6e899c3f296d)

Un Saludo

**Comment by mdiago** [comment]
Muchas gracias, hemos modificado el archivo de proyecto para incluir los cambios.
