### ISSUE TITLE
Instalar el paquete con el administrador de paquetes NuGet es para NET Core

### ISSUE THREAD

**Issue by PGSoftIberica** [mdiago/VeriFactu#19]
Buenas tardes no me aparece para .net framework 4.8  
es posible hacer compatible  via nuget 
Un Saludo

**Comment by mdiago** [comment]
Debería aparecerte, lo incluimos en la última versión del paquete:

![image](https://github.com/user-attachments/assets/6d6cbcdd-37b7-4c66-a022-62518778ca31)

He realizado la prueba en un proyecto de NET Framework de Windows Forms y si que aparece:

![image](https://github.com/user-attachments/assets/a341f1ae-8a83-4058-9b15-05884ad4117a)

![image](https://github.com/user-attachments/assets/5f9eb69f-3b46-42a5-86cc-01fe88ffbcca)

¿ Puede probar otra vez y nos dices ? Gracias.

**Comment by PGSoftIberica** [comment]
Buenos dias, si pude agregar. Como pone para .net core tambien es compatible con .net framenwork 4.8 o posterior
Gracias
