### ISSUE TITLE
Envio con IRPF

### ISSUE THREAD

**Issue by PGSoftIberica** [mdiago/VeriFactu#4]
hola, un ejemplo con IRPF, y con recargo de equivalencia para poder abarcar tadas la posibilidades
Un Saludo

**Comment by mdiago** [comment]
Acabamos de subir los cambios necesarios para el recargo de equivalencia. En el ejemplo siguiente se muestra un envío:

```C#

// Creamos una instacia de la clase factura
var invoice = new Invoice("TS08-001-021", new DateTime(2024, 10, 14), "B72877814")
{
    InvoiceType = TipoFactura.F1,
    SellerName = "WEFINZ GANDIA SL",
    BuyerID = "B44531218",
    BuyerName = "WEFINZ SOLUTIONS SL",
    Text = "VENTA A COMERCIO MINORISTA",
    TaxItems = new List<TaxItem>() {
        new TaxItem()
        {
            TaxScheme = ClaveRegimen.RecEquivPeqEmp,
            TaxType = CalificacionOperacion.S1,
            TaxRate = 21,
            TaxBase = 1000,
            TaxAmount = 210m,
            TaxRateSurcharge = 5.2m,
            TaxAmountSurcharge = 52m
        }
    }
};

// Creamos la entrada de la factura
var invoiceEntry = new InvoiceEntry(invoice);

// Guardamos la factura
invoiceEntry.Save();

// Consultamos el resultado devuelto por la AEAT
Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.Response}");


```

**Comment by mdiago** [comment]
Respecto al IRPF, tendremos que consultar con la AEAT qué se debe hacer, ya que no hemos encontrado nada al respecto ni en la documentación ni en las FAQs. 
Hemos hecho pruebas de envío y hemos conseguido que el sistema acepte el siguiente xml:

![image](https://github.com/user-attachments/assets/aa7f6d12-46d1-4d73-8df6-894de474ee32)

El problema es que infringe la siguiente validación del documento de validaciones:

![image](https://github.com/user-attachments/assets/1f8daf69-f36a-4c54-96b2-b73b26031477)

Y además no tenemos clara la inclusión de una retención en el campo CuotaRepercutida. Haremos la consulta a la AEAT para que nos indiquen cómo debemos proceder.

**Comment by PGSoftIberica** [comment]
Gracias

Un Saludo

 

De: Manuel Diago Garcia ***@***.***> 
Enviado el: domingo, 3 de noviembre de 2024 19:58
Para: mdiago/VeriFactu ***@***.***>
CC: PGSoft Iberica ***@***.***>; Author ***@***.***>
Asunto: Re: [mdiago/VeriFactu] Envio con IRPF (Issue #4)

 

Acabamos de subir los cambios necesarios para el recargo de equivalencia. En el ejemplo siguiente se muestra un envío:

// Creamos una instacia de la clase factura
var invoice = new Invoice("TS08-001-021", new DateTime(2024, 10, 14), "B72877814")
{
    InvoiceType = TipoFactura.F1,
    SellerName = "WEFINZ GANDIA SL",
    BuyerID = "B44531218",
    BuyerName = "WEFINZ SOLUTIONS SL",
    Text = "VENTA A COMERCIO MINORISTA",
    TaxItems = new List<TaxItem>() {
        new TaxItem()
        {
            TaxScheme = ClaveRegimen.RecEquivPeqEmp,
            TaxType = CalificacionOperacion.S1,
            TaxRate = 21,
            TaxBase = 1000,
            TaxAmount = 210m,
            TaxRateSurcharge = 5.2m,
            TaxAmountSurcharge = 52m
        }
    }
};
 
// Creamos la entrada de la factura
var invoiceEntry = new InvoiceEntry(invoice);
 
// Guardamos la factura
invoiceEntry.Save();
 
// Consultamos el resultado devuelto por la AEAT
Debug.Print($"Respuesta de la AEAT:\n{invoiceEntry.Response}");

**Comment by PGSoftIberica** [comment]
Gracias, haber que responde AEAT pues es creo un punto importante

Un Saludo

 

 

De: Manuel Diago Garcia ***@***.***> 
Enviado el: domingo, 3 de noviembre de 2024 20:11
Para: mdiago/VeriFactu ***@***.***>
CC: PGSoft Iberica ***@***.***>; Author ***@***.***>
Asunto: Re: [mdiago/VeriFactu] Envio con IRPF (Issue #4)

 

Respecto al IRPF, tendremos que consultar con la AEAT qué se debe hacer, ya que no hemos encontrado nada al respecto ni en la documentación ni en las FAQs.
Hemos hecho pruebas de envío y hemos conseguido que el sistema acepte el siguiente xml:

image.png (view on web) <https://github.com/user-attachments/assets/aa7f6d12-46d1-4d73-8df6-894de474ee32> 

El problema es que infringe la siguiente validación del documento de validaciones:

image.png (view on web) <https://github.com/user-attachments/assets/1f8daf69-f36a-4c54-96b2-b73b26031477> 

Y además no tenemos clara la inclusión de una retención en el campo CuotaRepercutida. Haremos la consulta a la AEAT para que nos indiquen cómo debemos proceder.

**Comment by mdiago** [comment]
Desde la AEAT han respondido a nuestra consulta sobre las retenciones, y en principio parece que no se informan en los registros de alta de VERI*FACTU, de manera análoga al SII. Adjunto el fragmento de la respuesta de la AEAT dónde lo exponen:

"La factura, desde el punto de vista fiscal, se encuentra regulada en el RD 1619/2012 que aprueba el reglamento que regula la obligación de expedir Factura. Las menciones de factura, estrictamente hablando son las que aparecen en el artículo 6 del referido Reglamento, sin que se incluyan las retenciones a cuenta o las retenciones de garantía. No obstante debe señalarse que esas menciones de factura no excluyen "las que puedan resultar obligatorias a otros efectos" por lo que perfectamente pueden incluirse suplidos, retenciones de IRPF de profesionales, retenciones de garantía en obra, etc. Esas otras menciones, así como los importes que correspondan no deben alterar el "Importe Total Factura" que se configura como Base Imponible del IVA + Cuota de IVA, sino que podrán consignarse en otros posibles campos de la factura (que no se recogen en el registro de facturación de alta) como "Total a Pagar", "Total Retenido" etc. para ser utilizados en las aplicaciones de gestión como corresponda."

**Comment by PGSoftIberica** [comment]
de todas formas sería interesante tener un ejemplo con irpf al 15% que es el mas comunun saludo El 5 nov 2024, a las 10:08, Manuel Diago Garcia ***@***.***> escribió:﻿
Desde la AEAT han respondido a nuestra consulta sobre las retenciones, y en principio parece que no se informan en los registros de alta de VERI*FACTU, de manera análoga al SII. Adjunto el fragmento de la respuesta de la AEAT dónde lo exponen:
"La factura, desde el punto de vista fiscal, se encuentra regulada en el RD 1619/2012 que aprueba el reglamento que regula la obligación de expedir Factura. Las menciones de factura, estrictamente hablando son las que aparecen en el artículo 6 del referido Reglamento, sin que se incluyan las retenciones a cuenta o las retenciones de garantía. No obstante debe señalarse que esas menciones de factura no excluyen "las que puedan resultar obligatorias a otros efectos" por lo que perfectamente pueden incluirse suplidos, retenciones de IRPF de profesionales, retenciones de garantía en obra, etc. Esas otras menciones, así como los importes que correspondan no deben alterar el "Importe Total Factura" que se configura como Base Imponible del IVA + Cuota de IVA, sino que podrán consignarse en otros posibles campos de la factura (que no se recogen en el registro de facturación de alta) como "Total a Pagar", "Total Retenido" etc. para ser utilizados en las aplicaciones de gestión como corresponda."

**Comment by PGSoftIberica** [comment]
y los autonomos que hacen la factura como se podra gestionar ?un saludo Enviado desde mi iPhoneEl 5 nov 2024, a las 10:44, Manuel Diago Garcia ***@***.***> escribió:﻿
No podemos tener un ejemplo con IRPF ya que el IRPF y resto de retenciones queda fuera del ámbito de Verifactu y por tanto de la funcionalidad de la librería.
